### ISSUE TITLE
devices command not working

### ISSUE THREAD

**Issue by shtnkgm** [yahoojapan/XCMetricsAggregator#9]
feature/gem branch

```bash
$ bundle exec exe/xcmagg devices

bundler: failed to load command: exe/xcmagg (exe/xcmagg)
NoMethodError: undefined method `split' for nil:NilClass
  /Users/snakagam/Desktop/XCMetricsAggregator/lib/xc_metrics_aggregator.rb:36:in `devices'
  /Users/snakagam/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
  /Users/snakagam/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/snakagam/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
  /Users/snakagam/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
  exe/xcmagg:5:in `<top (required)>'
MBP-13JAU-233:XCMetricsAggregator snakagam$ 
```

**Comment by kazuhiro4949** [comment]
It's fixed 

https://github.com/yahoojapan/XCMetricsAggregator/pull/3/commits/a305b2fc05e13a9e3e040907cdb5d89d4a186a5f
